Repository NibiruChain/nibiru, pull requests merged in 2022-11, with the labels that each got.

#1045 docs: Update docs link
  README.md
Labels: documentation, Skip-Changelog

#1033 feat(collections): change `IndexedMap.Iterate` to accept generic `Ranger` interface
  collections/indexed_map.go
Labels: Skip-Changelog

#1048 docs: fix changelog to include v0.15.0 section
  CHANGELOG.md
Labels: documentation, Skip-Changelog

#1031 chore: http gateway annotations in oracle
  proto/oracle/v1beta1/tx.proto
  x/oracle/types/tx.pb.go
  x/oracle/types/tx.pb.gw.go
Labels: Skip-Changelog

#1081 test: add additional PositionChangedEvent test
  x/perp/keeper/clearing_house_integration_test.go
  x/perp/keeper/clearing_house_unit_test.go
Labels: Skip-Changelog

#1083 refactor(testutil): Less repetition. Move PassGovProposal to x/testutil
  CHANGELOG.md
  x/pricefeed/client/cli/cli_test.go
  x/testutil/cli/gov.go
  x/vpool/client/cli/cli_test.go
Labels: refactor, Skip-Changelog

#1085 fix: pin cosmos-sdk version to v0.45.10
  scripts/protocgen.sh
Labels: Skip-Changelog

#1086 refactor(perp)!: Removed unused field, `LiquidationPenalty`, from `PositionChangedEvent`
  CHANGELOG.md
  proto/perp/v1/event.proto
  x/perp/keeper/clearing_house.go
  x/perp/keeper/clearing_house_integration_test.go
  x/perp/keeper/clearing_house_unit_test.go
  x/perp/keeper/margin.go
  x/perp/keeper/margin_test.go
  x/perp/keeper/margin_unit_test.go
  x/perp/types/event.pb.go
Labels: refactor
