Repository NibiruChain/nibiru, pull requests merged in 2023-01, with the labels that each got.

#1126 refactor(perp): Remove unnecessary panics | #1
  CHANGELOG.md
  x/common/common_test.go
  x/common/error.go
  x/common/error_test.go
  x/common/set.go
  x/common/set_test.go
  x/oracle/keeper/tally_fuzz_test.go
  x/oracle/keeper/vote_target_test.go
  x/perp/keeper/clearing_house.go
  x/perp/keeper/margin.go
  x/perp/keeper/perp.go
  x/perp/simulation/operations.go
Labels: tests, refactor

#1127 refactor: Remove unnecessary panics | #2 dex and stablecoin
  CHANGELOG.md
  x/dex/client/cli/flags.go
  x/dex/client/cli/tx.go
  x/dex/keeper/grpc_query.go
  x/dex/keeper/keeper.go
  x/dex/keeper/keeper_test.go
  x/dex/keeper/liquidity.go
  x/dex/keeper/liquidity_test.go
  x/dex/keeper/swap.go
  x/dex/simulation/operations.go
  x/dex/types/errors.go
  x/dex/types/pool_test.go
  x/oracle/simulation/genesis.go
  x/stablecoin/keeper/mint_burn_stable.go
Labels: refactor

#1140 fix: set vote period to 10 blocks
  scripts/localnet.sh
Labels: Skip-Changelog

#1141 refactor(oracle): rename functions and variables for readability
  CHANGELOG.md
  x/oracle/genesis.go
  x/oracle/genesis_test.go
  x/oracle/keeper/ballot.go
  x/oracle/keeper/ballot_test.go
  x/oracle/keeper/keeper.go
  x/oracle/keeper/querier_test.go
  x/oracle/keeper/reward.go
  x/oracle/keeper/reward_test.go
  x/oracle/keeper/slash_test.go
  x/oracle/keeper/tally.go
  x/oracle/keeper/tally_fuzz_test.go
  x/oracle/keeper/test_utils.go
  x/oracle/keeper/update_exchange_rates.go
  x/oracle/keeper/update_exchange_rates_test.go
  x/oracle/keeper/vote_target.go
  x/oracle/keeper/vote_target_test.go
  x/oracle/types/ballot.go
  x/oracle/types/ballot_test.go
Labels: enhancement

#1107 ci: Create wasm e2e test
  .github/workflows/e2e-wasm.yml
  CHANGELOG.md
  Dockerfile-build
  scripts/e2e/contracts/cw_nameservice.wasm
  scripts/e2e/deploy-wasm.sh
  scripts/e2e/localnet.sh
Labels: tests

#1145 chore: add USD quote asset
  CHANGELOG.md
  x/common/common.go
Labels: enhancement

#1146 chore: fix local docker-compose network
  CHANGELOG.md
  Dockerfile
  cmd/nibid/cmd/testnet.go
  contrib/docker-compose/docker-compose.yml
  contrib/make/localnet.mk
  contrib/make/proto.mk
  contrib/scripts/docker-wrapper.sh
  contrib/scripts/localnet.sh
  contrib/scripts/protocgen-any.sh
  contrib/scripts/protocgen.sh
  contrib/scripts/testing/stableswap_model.py
  x/oracle/types/state.pb.go
  x/stablecoin/types/tx.pb.go
Labels: bug, refactor, enhancement

#1142 refactor: build workflows
  .github/workflows/docker-publish.yml
  .github/workflows/docker-release.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/goreleaser.yml
  .github/workflows/integration-tests.yml
  .github/workflows/sims.yml
  .github/workflows/unit-tests.yml
Labels: refactor, Skip-Changelog

#1155 fix: localnet scripts
  .github/workflows/e2e-wasm.yml
  contrib/scripts/e2e/contracts/cw_nameservice.wasm
  contrib/scripts/e2e/deploy-wasm.sh
  contrib/scripts/e2e/localnet.sh
  contrib/scripts/localnet.sh
Labels: Skip-Changelog

#1157 ci(docker-publish.yml): fixes yaml syntax error
  .github/workflows/docker-publish.yml
Labels: fix/bug, Skip-Changelog

#1160 feat: add generic sets
  CHANGELOG.md
  x/common/asset_registry.go
  x/common/set.go
  x/common/set/set.go
  x/common/set/set_test.go
  x/oracle/keeper/tally_fuzz_test.go
Labels: enhancement

#1159 refactor(asset_registry): Use `set[string]` instead of slice `[]string`, since it covers both use cases
  CHANGELOG.md
  x/common/asset_registry.go
  x/common/asset_registry_test.go
  x/common/set.go
  x/common/set/set.go
  x/common/set/set_test.go
  x/oracle/keeper/tally_fuzz_test.go
Labels: refactor, Skip-Changelog

#1139 feat: set default oracle whitelisted pairs
  .github/workflows/golangci-lint.yml
  CHANGELOG.md
  x/oracle/types/params.go
Labels: enhancement
