Repository NibiruChain/nibiru, pull requests merged in 2023-09, with the labels that each got.

#1590 revert(gha): use checkout and codecov action v3
  .github/workflows/changelog-deps.yml
  .github/workflows/coverage.yml
  .github/workflows/docker-publish.yml
  .github/workflows/e2e-wasm.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/goreleaser.yml
  .github/workflows/integration-tests.yml
  .github/workflows/proto-lint.yml
  .github/workflows/sims.yml
  .github/workflows/unit-tests.yml
Labels: skip-changelog

#1591 refactor(gha): simplify integration test workflows
  .github/workflows/coverage.yml
  .github/workflows/integration-tests.yml
  .github/workflows/unit-tests.yml
  contrib/make/test.mk
Labels: skip-changelog

#1597 ci: fix coverage report publishing
  .github/workflows/integration-tests.yml
  contrib/make/test.mk
  x/perp/v2/keeper/clearing_house.go
Labels: type: tests, skip-changelog

#1604 chore: msg interfaces
  x/perp/v2/types/msgs.go
  x/spot/types/message.go
  x/stablecoin/types/messages.go
  x/sudo/types/msgs.go
Labels: skip-changelog

#1610 refactor(app): Simplify app.go with less redundant imports using struct embedding.
  CHANGELOG.md
  app/app.go
  app/keepers.go
Labels: type: refactor

#1613 feat(app)!: enforce min commission by changing default and genesis validation
  CHANGELOG.md
  app/modules.go
  app/modules_test.go
  app/sim/config.go
  cmd/nibid/cmd/root.go
  simapp/sim_test.go
  simapp/state_test.go
Labels: type: enhancement
