Repository NibiruChain/nibiru, pull requests merged in 2023-02, with the labels that each got.

#1168 fix: remove ampersand
  contrib/scripts/localnet.sh
Labels: Skip-Changelog

#1162 fix: multi-platform docker image
  Dockerfile
Labels: Skip-Changelog

#1176 refactor(spot): remove remaining dex files
  CHANGELOG.md
  x/dex/genesis_test.go
  x/dex/keeper/liquidity_test.go
  x/dex/keeper/params_test.go
  x/dex/keeper/swap_test.go
  x/spot/keeper/liquidity_test.go
Labels: refactor

#1144 ci(release): release for linux and darwin (arm64 and amd64)
  .github/workflows/goreleaser.yml
  .goreleaser.yml
  CHANGELOG.md
  Makefile
  contrib/make/release.mk
  go.mod
  go.sum
Labels: dependencies

#1180 refactor(oracle): whitelist
  CHANGELOG.md
  x/oracle/keeper/ballot.go
  x/oracle/keeper/ballot_test.go
  x/oracle/keeper/whitelist.go
  x/oracle/keeper/whitelist_test.go
Labels: refactor

#1181 refactor(oracle): keeper files
  CHANGELOG.md
  x/oracle/keeper/ballot.go
  x/oracle/keeper/ballot_test.go
  x/oracle/keeper/tally.go
  x/oracle/keeper/tally_fuzz_test.go
  x/oracle/keeper/update_exchange_rates.go
  x/oracle/keeper/whitelist.go
  x/oracle/keeper/whitelist_test.go
Labels: refactor

#1184 refactor(oracle): proto type docs, (2) oracle spec clean-up, and (3) remove panic
  CHANGELOG.md
  Makefile
  contrib/scripts/e2e/deploy-wasm.sh
  contrib/scripts/protocgen.sh
  proto/oracle/v1beta1/oracle.proto
  proto/oracle/v1beta1/tx.proto
  x/oracle/README.md
  x/oracle/genesis.go
  x/oracle/keeper/keeper.go
  x/oracle/keeper/msg_server.go
  x/oracle/keeper/params.go
  x/oracle/spec/01_concepts.md
  x/oracle/spec/02_state.md
  x/oracle/spec/03_end_block.md
  x/oracle/spec/04_messages.md
  x/oracle/spec/05_events.md
  x/oracle/spec/06_params.md
  x/oracle/spec/README.md
  x/oracle/types/oracle.pb.go
  x/oracle/types/tx.pb.go
Labels: documentation, refactor

#1187 feat(oracle): default vote threshold and min voters
  .golangci.yml
  CHANGELOG.md
  proto/oracle/v1beta1/oracle.proto
  x/oracle/keeper/ballot.go
  x/oracle/keeper/ballot_test.go
  x/oracle/keeper/keeper_test.go
  x/oracle/keeper/params.go
  x/oracle/keeper/querier_test.go
  x/oracle/keeper/reward_test.go
  x/oracle/keeper/slash_test.go
  x/oracle/keeper/update_exchange_rates.go
  x/oracle/keeper/update_exchange_rates_test.go
  x/oracle/types/ballot.go
  x/oracle/types/oracle.pb.go
  x/oracle/types/params.go
  x/oracle/types/params_test.go
Labels: enhancement

#1191 fix(oracle): default oracle whitelist
  CHANGELOG.md
  x/oracle/types/params.go
Labels: refactor

#1192 feat: docker-compose network for local development
  .github/workflows/docker-publish.yml
  CHANGELOG.md
  CHAOSNET.md
  Dockerfile-build
  contrib/docker-compose/docker-compose-chaosnet.yml
  contrib/docker-compose/docker-compose-multi-node.yml
  contrib/docker/chaosnet.Dockerfile
  contrib/docker/linux.Dockerfile
  contrib/make/chaosnet.mk
  contrib/make/localnet.mk
  contrib/scripts/chaosnet.sh
  contrib/templates/bdjuno.yaml
Labels: enhancement

#1193 refactor(oracle): clean up tests
  CHANGELOG.md
  x/oracle/abci_test.go
  x/oracle/genesis.go
  x/oracle/genesis_test.go
  x/oracle/integration_test/app_test.go
  x/oracle/keeper/alias_functions.go
  x/oracle/keeper/ballot.go
  x/oracle/keeper/ballot_test.go
  x/oracle/keeper/keeper.go
  x/oracle/keeper/keeper_test.go
  x/oracle/keeper/msg_server_test.go
  x/oracle/keeper/params_test.go
  x/oracle/keeper/querier_test.go
  x/oracle/keeper/reward.go
  x/oracle/keeper/reward_test.go
  x/oracle/keeper/slash_test.go
  x/oracle/keeper/test_utils.go
  x/oracle/keeper/update_exchange_rates_test.go
  x/oracle/keeper/whitelist_test.go
  x/oracle/types/test_utils.go
Labels: tests

#1194 fix(oracle): local min voters
  CHANGELOG.md
  contrib/make/chaosnet.mk
  contrib/scripts/chaosnet.sh
  contrib/scripts/localnet.sh
Labels: fix/bug

#1195 feat(perp): multi liquidate
  CHANGELOG.md
  contrib/scripts/localnet.sh
  proto/perp/v1/event.proto
  proto/perp/v1/tx.proto
  x/common/testutil/cli/network.go
  x/perp/client/cli/cli_test.go
  x/perp/client/cli/tx.go
  x/perp/keeper/calc_test.go
  x/perp/keeper/calc_unit_test.go
  x/perp/keeper/clearing_house_integration_test.go
  x/perp/keeper/clearing_house_unit_test.go
  x/perp/keeper/grpc_query_test.go
  x/perp/keeper/hooks_test.go
  x/perp/keeper/liquidate.go
  x/perp/keeper/liquidate_test.go
  x/perp/keeper/liquidate_unit_test.go
  x/perp/keeper/margin_test.go
  x/perp/keeper/margin_unit_test.go
  x/perp/keeper/msg_server.go
  x/perp/keeper/msg_server_test.go
  x/perp/keeper/perp_test.go
  x/perp/keeper/perp_unit_test.go
  x/perp/keeper/testutil.go
  x/perp/types/event.pb.go
  x/perp/types/msgs_test.go
  x/perp/types/tx.pb.go
  x/perp/types/types.go
Labels: fix/bug, epic

#1197 refactor(testutil): deduplicate simapp setup
  CHANGELOG.md
  app/ante.go
  app/antedecorators/fee/testutil_test.go
  app/ibc_test.go
  simapp/sim_test.go
  simapp/testapp.go
  x/common/testutil/cli/network.go
  x/common/testutil/genesis/genesis.go
  x/common/testutil/testapp/config.go
  x/common/testutil/testapp/genesis.go
  x/common/testutil/testapp/testapp.go
  x/common/testutil/testapp/testapp_test.go
  x/epochs/abci_test.go
  x/epochs/genesis_test.go
  x/epochs/keeper/grpc_query_test.go
  x/epochs/keeper/keeper_test.go
  x/oracle/integration_test/app_test.go
  x/perp/client/cli/cli_test.go
  x/perp/genesis_test.go
  x/perp/keeper/calc_test.go
  x/perp/keeper/clearing_house_integration_test.go
  x/perp/keeper/grpc_query_test.go
  x/perp/keeper/keeper_test.go
  x/perp/keeper/liquidate_test.go
  x/perp/keeper/margin_test.go
  x/perp/keeper/msg_server_test.go
  x/perp/keeper/perp_test.go
  x/perp/module_test.go
  x/perp/types/expected_keepers_test.go
  x/spot/client/testutil/cli_test.go
  x/spot/client/testutil/test_helpers.go
  x/spot/genesis_test.go
  x/spot/keeper/balances_test.go
  x/spot/keeper/grpc_query_test.go
  x/spot/keeper/keeper_test.go
  x/spot/keeper/liquidity_test.go
  x/spot/keeper/msg_server_test.go
  x/spot/keeper/params_test.go
  x/spot/keeper/swap_test.go
  x/stablecoin/abci_test.go
  x/stablecoin/client/cli/cli_test.go
  x/stablecoin/genesis_test.go
  x/stablecoin/keeper/collateral_ratio_test.go
  x/stablecoin/keeper/grpc_query_test.go
  x/stablecoin/keeper/keeper_test.go
  x/stablecoin/keeper/mint_burn_stable_test.go
  x/stablecoin/keeper/msg_server_test.go
  x/stablecoin/keeper/params_test.go
  x/stablecoin/keeper/supply_test.go
  x/stablecoin/module_simulation.go
  x/stablecoin/types/expected_keepers_test.go
  x/util/keeper/query_server_test.go
  x/vpool/abci_test.go
  x/vpool/client/cli/cli_test.go
  x/vpool/genesis_test.go
  x/wasm/cli/cli_test.go
Labels: tests, refactor, enhancement

#1196 refactor(spot)!: default pool params and cli commands
  CHANGELOG.md
  x/spot/client/cli/query.go
  x/spot/types/params.go
Labels: refactor

#1198 feat: add explanation for error in chaosnet installation
  .github/workflows/docker-publish.yml
  CHAOSNET.md
Labels: Skip-Changelog
