Repository NibiruChain/nibiru, pull requests merged in 2023-07, with the labels that each got.

#1466 refactor(perp)!: PositionLiquidatedEvent
  CHANGELOG.md
  proto/nibiru/perp/v2/event.proto
  x/perp/v2/keeper/liquidate.go
  x/perp/v2/types/change_reason.go
  x/perp/v2/types/event.pb.go
  x/perp/v2/types/position.go
Labels: type: refactor, type: enhancement

#1473 refactor(perp)!: rename OpenPosition to MarketOrder
  CHANGELOG.md
  proto/nibiru/perp/v2/tx.proto
  x/perp/v2/client/cli/cli_test.go
  x/perp/v2/client/cli/tx.go
  x/perp/v2/integration/action/position.go
  x/perp/v2/integration/action/tx.go
  x/perp/v2/keeper/clearing_house.go
  x/perp/v2/keeper/clearing_house_test.go
  x/perp/v2/keeper/margin_test.go
  x/perp/v2/keeper/msg_server.go
  x/perp/v2/keeper/msg_server_test.go
  x/perp/v2/module/handler.go
  x/perp/v2/types/change_reason.go
  x/perp/v2/types/codec.go
  x/perp/v2/types/msgs.go
  x/perp/v2/types/tx.pb.go
  x/perp/v2/types/tx.pb.gw.go
  x/wasm/binding/cw_struct/cw_msg.go
  x/wasm/binding/cw_struct/cw_test.go
  x/wasm/binding/cw_struct/execute_msg.json
  x/wasm/binding/exec.go
  x/wasm/binding/exec_perp.go
  x/wasm/binding/exec_perp_test.go
  x/wasm/binding/exec_test.go
  x/wasm/binding/querier_perp_test.go
  x/wasm/binding/wasmbin/bindings_perp.wasm
Labels: type: refactor, dependencies

#1476 fix(wasm)!: call `ValidateBasic` before all `sdk.Msg` calls for the bindings-perp contract + remove sudo permissioning
  CHANGELOG.md
  x/wasm/binding/exec.go
  x/wasm/binding/exec_perp.go
  x/wasm/binding/exec_perp_test.go
  x/wasm/binding/exec_test.go
  x/wasm/binding/querier_perp_test.go
  x/wasm/binding/querier_test.go
Labels: type: fix/bug

#1475 fix(perp): event field assertion tests
  go.mod
  x/oracle/simulation/decoder.go
  x/oracle/simulation/decoder_test.go
  x/perp/v2/integration/assertion/event.go
  x/spot/keeper/grpc_query.go
  x/spot/keeper/keeper.go
  x/stablecoin/client/cli/cli_test.go
  x/sudo/cli/cli_test.go
Labels: type: fix/bug, type: tests, skip-changelog

#1467 fix(oracle): make calcTwap safer
  CHANGELOG.md
  x/oracle/keeper/keeper.go
Labels: type: fix/bug, type: refactor

#1478 fix(test): position changed event comparison
  x/common/testutil/events.go
  x/perp/v2/integration/assertion/event.go
  x/perp/v2/keeper/liquidate_test.go
Labels: type: fix/bug, type: tests, skip-changelog

#1479 feat(perp): PartialClose
  CHANGELOG.md
  proto/nibiru/perp/v2/tx.proto
  x/common/testutil/events.go
  x/perp/v2/client/cli/cli_test.go
  x/perp/v2/client/cli/tx.go
  x/perp/v2/integration/action/margin.go
  x/perp/v2/integration/action/market.go
  x/perp/v2/integration/action/position.go
  x/perp/v2/keeper/clearing_house.go
  x/perp/v2/keeper/clearing_house_test.go
  x/perp/v2/keeper/margin_test.go
  x/perp/v2/keeper/msg_server.go
  x/perp/v2/types/amm.go
  x/perp/v2/types/change_reason.go
  x/perp/v2/types/codec.go
  x/perp/v2/types/msgs.go
  x/perp/v2/types/tx.pb.go
Labels: type: enhancement

#1491 refactor: fix some non conventional issues on sudo module
  app/app.go
  app/keepers.go
  x/common/testutil/cli/query.go
  x/common/testutil/genesis/sudo_genesis.go
  x/sudo/cli/cli.go
  x/sudo/cli/cli_test.go
  x/sudo/genesis.go
  x/sudo/keeper/querier.go
  x/sudo/keeper/sudo.go
  x/sudo/keeper/sudo_test.go
  x/sudo/module.go
  x/sudo/pb/actions.go
  x/sudo/types/actions.go
  x/sudo/types/codec.go
  x/sudo/types/event.pb.go
  x/sudo/types/msgs.go
  x/sudo/types/query.pb.go
  x/sudo/types/query.pb.gw.go
  x/sudo/types/state.go
  x/sudo/types/state.pb.go
  x/sudo/types/tx.pb.go
  x/sudo/types/tx.pb.gw.go
  x/wasm/binding/exec.go
  x/wasm/binding/wasm.go
Labels: skip-changelog

#1496 ci(chaosnet): fix chaosnet for v0.21
  CHAOSNET.md
  contrib/docker-compose/docker-compose-chaosnet.yml
  contrib/make/chaosnet.mk
  contrib/scripts/chaosnet.sh
  contrib/scripts/localnet.sh
Labels: skip-changelog

#1493 feat(perp): ClosePosition with bad debt
  CHANGELOG.md
  x/perp/v2/integration/action/market.go
  x/perp/v2/integration/action/position.go
  x/perp/v2/integration/assertion/event.go
  x/perp/v2/integration/assertion/position.go
  x/perp/v2/keeper/clearing_house.go
  x/perp/v2/keeper/clearing_house_test.go
  x/perp/v2/keeper/margin_test.go
  x/perp/v2/types/errors.go
Labels: type: enhancement

#1460 refactor: remove unnecessary module methods
  CHANGELOG.md
  x/epochs/handler.go
  x/epochs/module.go
  x/epochs/types/codec.go
  x/inflation/module.go
  x/perp/v2/module/module.go
  x/perp/v2/types/codec.go
  x/spot/module.go
  x/spot/types/codec.go
  x/stablecoin/handler.go
  x/stablecoin/module.go
  x/stablecoin/types/codec.go
  x/sudo/module.go
  x/sudo/types/codec.go
Labels: type: refactor

#1500 refactor(perp): reverse market order
  CHANGELOG.md
  x/perp/v2/integration/action/position.go
  x/perp/v2/integration/assertion/position.go
  x/perp/v2/keeper/clearing_house.go
  x/perp/v2/keeper/clearing_house_test.go
  x/perp/v2/keeper/grpc_query.go
Labels: type: refactor

#1503 feat: add wasm oracle exchange rate query
  CHANGELOG.md
  x/wasm/binding/cw_struct/cw_query.go
  x/wasm/binding/cw_struct/cw_test.go
  x/wasm/binding/cw_struct/query_resp.json
  x/wasm/binding/querier.go
  x/wasm/binding/querier_perp_test.go
  x/wasm/binding/querier_test.go
  x/wasm/binding/wasm.go
  x/wasm/binding/wasmbin/bindings_perp.wasm
  x/wasm/binding/wasmbin/controller.wasm
  x/wasm/binding/wasmbin/shifter.wasm
Labels: type: enhancement

#1511 fix: update localnet script
  contrib/scripts/localnet.sh
Labels: skip-changelog
