Repository NibiruChain/nibiru, pull requests merged in 2023-05, with the labels that each got.

#1301 fix(epochs)!: correct epoch start time
  CHANGELOG.md
  x/common/testutil/testapp/testapp.go
  x/epochs/abci.go
  x/epochs/abci_test.go
  x/epochs/genesis_test.go
  x/epochs/keeper/grpc_query_test.go
  x/epochs/keeper/keeper_test.go
  x/epochs/types/genesis.go
  x/perp/keeper/margin.go
Labels: type: fix/bug

#1300 feat(actions): add mandatory return parameter
  x/common/testutil/action/account.go
  x/common/testutil/action/balances.go
  x/common/testutil/action/block.go
  x/common/testutil/action/testcase.go
  x/common/testutil/assertion/gas.go
  x/oracle/integration_test/action/price.go
  x/perp/amm/integration/action/config.go
  x/perp/amm/integration/assertion/vpool.go
  x/perp/integration/action/liquidation.go
  x/perp/integration/action/params.go
  x/perp/integration/action/position.go
  x/perp/integration/action/vpool.go
  x/perp/integration/assertion/event.go
  x/perp/integration/assertion/position.go
Labels: Skip-Changelog

#1305 refactor(perp)!: Remove unnecessary protos
  CHANGELOG.md
  proto/perp/v2/event.proto
  proto/perp/v2/query.proto
  proto/perp/v2/state.proto
  x/perp/types/v2/event.pb.go
  x/perp/types/v2/query.pb.go
  x/perp/types/v2/query.pb.gw.go
  x/perp/types/v2/state.pb.go
Labels: type: refactor

#1299 feat(wasm): binding for peg shift + tests (2/3)
  CHANGELOG.md
  x/perp/keeper/amm.go
  x/wasm/binding/cw_struct/cw_msg.go
  x/wasm/binding/cw_struct/cw_query.go
  x/wasm/binding/cw_struct/cw_test.go
  x/wasm/binding/cw_struct/execute_msg.json
  x/wasm/binding/cw_struct/query_resp.json
  x/wasm/binding/exec.go
  x/wasm/binding/exec_perp.go
  x/wasm/binding/exec_perp_test.go
  x/wasm/binding/exec_test.go
  x/wasm/binding/querier.go
  x/wasm/binding/querier_perp_test.go
  x/wasm/binding/wasmbin/bindings_perp.wasm
Labels: type: tests, type: enhancement

#1319 test: add integration test actions for oracle, epochs, and common
  CHANGELOG.md
  x/common/testutil/action/account.go
  x/common/testutil/action/block.go
  x/common/testutil/action/testcase.go
  x/common/testutil/assertion/balances.go
  x/common/testutil/testapp/testapp.go
  x/epochs/integration/action/epoch.go
  x/oracle/integration/action/price.go
  x/oracle/integration/app_test.go
  x/perp/amm/keeper/bias_test.go
  x/perp/keeper/clearing_house_integration_test.go
  x/perp/keeper/open_gas_test.go
Labels: type: tests

#1320 fix: localnet script
  .github/workflows/e2e-wasm.yml
  contrib/scripts/localnet.sh
Labels: type: fix/bug, Skip-Changelog

#1330 docs: fix typos
  INSTALL.md
  README.md
Labels: skip-changelog

#1328 feat: add PerpKeeperV2 swap methods
  CHANGELOG.md
  x/perp/keeper/v2/swap.go
  x/perp/keeper/v2/swap_test.go
  x/perp/types/v2/amm.go
Labels: type: enhancement

#1329 feat(perp): add PerpKeeperV2 `Withdraw` method
  CHANGELOG.md
  x/perp/integration/action/v2/withdraw.go
  x/perp/keeper/v2/withdraw.go
  x/perp/keeper/v2/withdraw_test.go
Labels: type: enhancement

#1332 feat(perp): add hooks for updating funding rate
  CHANGELOG.md
  app/keepers.go
  x/perp/keeper/v2/hooks.go
  x/perp/keeper/v2/hooks_test.go
Labels: type: enhancement

#1333 feat(perp): add basic clearing house methods
  CHANGELOG.md
  x/perp/keeper/v2/calc.go
  x/perp/keeper/v2/calc_test.go
  x/perp/keeper/v2/clearing_house.go
Labels: type: enhancement

#1335 refactor(perp): move remaining files to v1 directory
  CHANGELOG.md
  app/app.go
  app/keepers.go
  x/perp/amm/keeper/bias_test.go
  x/perp/genesis.go
  x/perp/integration/action/v1/liquidation.go
  x/perp/integration/action/v1/params.go
  x/perp/integration/action/v1/position.go
  x/perp/integration/action/v1/vpool.go
  x/perp/integration/assertion/v1/event.go
  x/perp/integration/assertion/v1/position.go
  x/perp/keeper/v1/amm.go
  x/perp/keeper/v1/amm_test.go
  x/perp/keeper/v1/calc.go
  x/perp/keeper/v1/calc_test.go
  x/perp/keeper/v1/calc_unit_test.go
  x/perp/keeper/v1/clearing_house.go
  x/perp/keeper/v1/clearing_house_integration_test.go
  x/perp/keeper/v1/clearing_house_unit_test.go
  x/perp/keeper/v1/grpc_query.go
  x/perp/keeper/v1/grpc_query_test.go
  x/perp/keeper/v1/hooks.go
  x/perp/keeper/v1/hooks_test.go
  x/perp/keeper/v1/keeper.go
  x/perp/keeper/v1/keeper_test.go
  x/perp/keeper/v1/liquidate.go
  x/perp/keeper/v1/liquidate_test.go
  x/perp/keeper/v1/liquidate_unit_test.go
  x/perp/keeper/v1/margin.go
  x/perp/keeper/v1/margin_test.go
  x/perp/keeper/v1/margin_unit_test.go
  x/perp/keeper/v1/migrations.go
  x/perp/keeper/v1/migrations_test.go
  x/perp/keeper/v1/msg_server.go
  x/perp/keeper/v1/msg_server_test.go
  x/perp/keeper/v1/open_gas_test.go
  x/perp/keeper/v1/perp.go
  x/perp/keeper/v1/perp_test.go
  x/perp/keeper/v1/perp_unit_test.go
  x/perp/keeper/v1/testutil.go
  x/perp/keeper/v1/withdraw.go
  x/perp/keeper/v1/withdraw_test.go
  x/perp/module/v1/abci.go
  x/perp/module/v1/handler.go
  x/perp/module/v1/module.go
  x/perp/simulation/operations.go
  x/wasm/binding/exec.go
  x/wasm/binding/exec_perp.go
  x/wasm/binding/querier.go
  x/wasm/binding/wasm.go
Labels: type: refactor

#1334 feat(perp): add ClosePosition method
  CHANGELOG.md
  x/common/testutil/testapp/testapp.go
  x/perp/keeper/v2/clearing_house.go
  x/perp/keeper/v2/clearing_house_test.go
  x/perp/keeper/v2/twap_test.go
  x/perp/keeper/v2/withdraw_test.go
Labels: type: enhancement

#1340 feat(wasm): Enforce x/sudo contract permission checks on the shifter contract + integration tests
  CHANGELOG.md
  x/wasm/binding/exec.go
  x/wasm/binding/exec_test.go
  x/wasm/binding/wasmbin/bindings_perp.wasm
  x/wasm/binding/wasmbin/shifter.wasm
Labels: type: tests, type: enhancement

#1343 feat(perp): add liquidate method
  CHANGELOG.md
  x/perp/integration/action/v2/liquidation.go
  x/perp/keeper/v2/liquidate.go
  x/perp/keeper/v2/liquidate_test.go
  x/perp/keeper/v2/withdraw.go
Labels: type: refactor, type: enhancement

#1347 fix: revert to goleveldb for localnet
  contrib/make/build.mk
  contrib/scripts/localnet.sh
Labels: skip-changelog

#1348 ci: fetch librocksdb for local build
  .gitignore
  contrib/make/build.mk
Labels: skip-changelog

#1349 fix(build): fix missing rocksdb flag
  contrib/make/build.mk
  contrib/scripts/localnet.sh
Labels: skip-changelog

#1346 build: Upgrade wasmvm (v1.2.1), tendermint (v0.34.26), and Cosmos-SDK (v0.45.14) dependencies
  .goreleaser.yml
  CHANGELOG.md
  Dockerfile
  cmd/nibid/cmd/genwasm.go
  cmd/nibid/cmd/root.go
  go.mod
  go.sum
Labels: dependencies

#1350 feat(perp): EditPeg and EditSwapInvariant
  CHANGELOG.md
  x/common/testutil/action/balances.go
  x/common/testutil/assertion/balances.go
  x/perp/integration/action/v2/market.go
  x/perp/integration/assertion/v2/bank.go
  x/perp/integration/assertion/v2/market.go
  x/perp/keeper/v2/amm.go
  x/perp/keeper/v2/amm_test.go
  x/perp/keeper/v2/clearing_house.go
  x/perp/keeper/v2/clearing_house_test.go
  x/perp/types/v2/amm.go
  x/perp/types/v2/amm_test.go
  x/perp/types/v2/errors.go
Labels: type: refactor, type: enhancement

#1344 feat(perp): AddMargin and RemoveMargin methods
  CHANGELOG.md
  x/perp/integration/action/v2/margin.go
  x/perp/keeper/v2/margin.go
  x/perp/keeper/v2/margin_test.go
Labels: type: refactor, type: enhancement

#1352 feat(perp): PerpV2 msg server
  CHANGELOG.md
  x/perp/integration/action/v2/position.go
  x/perp/integration/action/v2/tx.go
  x/perp/keeper/v2/clearing_house.go
  x/perp/keeper/v2/clearing_house_test.go
  x/perp/keeper/v2/msg_server.go
  x/perp/keeper/v2/msg_server_test.go
Labels: type: refactor, type: enhancement

#1356 fix(deps): regress wasmvm dependency to working build
  .goreleaser.yml
  CHANGELOG.md
  Dockerfile
  go.mod
  go.sum
  x/perp/integration/action/v2/tx.go
Labels: type: fix/bug

#1363 feat(perp): wire perpv2 module
  CHANGELOG.md
  app/ante/fixed_gas.go
  app/ante/fixed_gas_test.go
  app/ante/testutil_test.go
  app/app.go
  app/genesis.go
  app/ibc_test.go
  app/keepers.go
  proto/perp/v2/genesis.proto
  proto/perp/v2/query.proto
  proto/perp/v2/state.proto
  x/oracle/genesis.go
  x/oracle/keeper/keeper.go
  x/oracle/keeper/params.go
  x/perp/client/cli/cli_test.go
  x/perp/keeper/v1/open_gas_test.go
  x/perp/keeper/v2/grpc_query.go
  x/perp/keeper/v2/keeper.go
  x/perp/module/v2/genesis.go
  x/perp/module/v2/genesis_test.go
  x/perp/types/v1/keys.go
  x/perp/types/v1/types.go
  x/perp/types/v2/genesis.go
  x/perp/types/v2/genesis.pb.go
  x/perp/types/v2/keys.go
  x/perp/types/v2/params.go
  x/perp/types/v2/query.pb.go
  x/perp/types/v2/query.pb.gw.go
  x/perp/types/v2/state.pb.go
Labels: type: refactor, type: enhancement

#1369 refactor(oracle): send rewards from perpv2 instead of perpv1
  CHANGELOG.md
  x/oracle/keeper/hooks.go
  x/oracle/keeper/hooks_test.go
Labels: type: refactor

#1370 feat(perp): CreatePool keeper method
  CHANGELOG.md
  x/perp/v2/integration/action/market.go
  x/perp/v2/keeper/admin.go
  x/perp/v2/keeper/admin_test.go
  x/perp/v2/module/abci.go
  x/perp/v2/module/abci_test.go
Labels: type: fix/bug, type: refactor, type: enhancement

#1372 fix: make localnet
  x/perp/v2/client/cli/cli_test.go
  x/perp/v2/types/keys.go
Labels: skip-changelog

#1386 fix: localnet script
  contrib/scripts/localnet.sh
  x/perp/v2/client/cli/cli_test.go
  x/perp/v2/client/cli/gen_market.go
  x/perp/v2/types/keys.go
Labels: skip-changelog

#1383 feat: enforce contract to be whitelisted when calling perp bindings
  CHANGELOG.md
  x/sudo/sudo.go
  x/wasm/binding/cw_struct/cw_msg.go
  x/wasm/binding/cw_struct/execute_msg.json
  x/wasm/binding/exec.go
  x/wasm/binding/exec_perp.go
  x/wasm/binding/exec_perp_test.go
  x/wasm/binding/exec_test.go
  x/wasm/binding/wasmbin/bindings_perp.wasm
  x/wasm/binding/wasmbin/controller.wasm
  x/wasm/binding/wasmbin/shifter.wasm
  x/wasm/binding/wasmbin_test.go
Labels: type: fix/bug

#1381 chore(deps): Bump github.com/cosmos/cosmos-sdk to 0.45.16
  .goreleaser.yml
  CHANGELOG.md
  INSTALL.md
  contrib/make/build.mk
  go.mod
  go.sum
Labels: do not merge
