Repository NibiruChain/nibiru, pull requests merged in 2023-06, with the labels that each got.

#1418 fix: fix build makefile
  contrib/make/build.mk
Labels: skip-changelog

#1430 Fix/v47
  contrib/devtools/Dockerfile
  contrib/make/proto.mk
  contrib/scripts/protocgen.sh
  proto/buf.gen.gogo.yml
  proto/buf.yaml
  x/perp/v2/types/event.pb.go
Labels: skip-changelog

#1434 feat(ci): build docker image on goreleaser
  .github/workflows/docker-chaosnet.yml
  .goreleaser.yml
  Dockerfile
  contrib/make/release.mk
Labels: skip-changelog

#1440 feat(make): link wasmvm statically and fix chaosnet
  .goreleaser.yml
  contrib/docker/chaosnet.Dockerfile
  contrib/make/build.mk
  contrib/scripts/chaosnet.sh
Labels: skip-changelog

#1442 ci: fix docker and goreleaser
  .github/workflows/docker-publish.yml
  .github/workflows/goreleaser.yml
  .goreleaser.yml
  Dockerfile
  contrib/docker/goreleaser.Dockerfile
  contrib/make/build.mk
  contrib/make/release.mk
Labels: skip-changelog

#1444 ci(proto): create ts protogen buf config file
  .github/workflows/proto-lint.yml
  proto/buf.gen.ts.yaml
Labels: skip-changelog

#1446 fix(root.go): add custom InitCmd that sets the desired Tendermint consensus parameters
  CHANGELOG.md
  cmd/nibid/cmd/init.go
  cmd/nibid/cmd/root.go
Labels: type: enhancement

#1447 fix(localnet): add sudo state and fix config
  contrib/scripts/localnet.sh
Labels: skip-changelog

#1452 fix(oracle): continue with abci hook during error
  CHANGELOG.md
  x/inflation/keeper/hooks.go
  x/oracle/keeper/reward.go
  x/oracle/keeper/slash.go
Labels: type: fix/bug

#1461 feat: add connect-es plugin
  proto/buf.gen.ts.yaml
Labels: skip-changelog, type: enhancement

#1459 fix(spot): wire msg service into router
  CHANGELOG.md
  x/common/testutil/cli/tx.go
  x/spot/client/testutil/cli_test.go
  x/spot/client/testutil/suite.go
  x/spot/client/testutil/test_helpers.go
  x/spot/handler.go
  x/spot/module.go
Labels: type: fix/bug

#1465 fix(proto): update ts proto gen config
  proto/buf.gen.ts.yaml
Labels: skip-changelog

#1463 feat(oracle): add genesis cmd to create pricefeeder delegation
  CHANGELOG.md
  cmd/nibid/cmd/root.go
  contrib/scripts/localnet.sh
  x/oracle/client/cli/gen_pricefeeder_delegation.go
  x/oracle/client/cli/gen_pricefeeder_delegation_test.go
Labels: type: enhancement

#1464 fix(gov): legacy proposals were not wired
  CHANGELOG.md
  app/keepers.go
Labels: type: fix/bug

#1462 fix(perp): add pair to liquidation failed events
  CHANGELOG.md
  proto/nibiru/perp/v2/tx.proto
  x/common/testutil/events.go
  x/perp/v2/integration/assertion/event.go
  x/perp/v2/keeper/liquidate.go
  x/perp/v2/keeper/liquidate_test.go
  x/perp/v2/types/tx.pb.go
Labels: type: tests, type: enhancement
