Repository NibiruChain/nibiru, pull requests merged in 2023-11, with the labels that each got.

#1652 test: refactors cli.network suites with 'Integration' to use common function
  .github/workflows/unit-tests.yml
  CHANGELOG.md
  contrib/make/test.mk
  simapp/sim_test.go
  wasmbinding/test/cli_test.go
  x/common/testutil/cases.go
  x/common/testutil/cases_test.go
  x/devgas/v1/keeper/grpc_query_test.go
  x/devgas/v1/keeper/keeper_test.go
  x/devgas/v1/keeper/msg_server_test.go
  x/perp/v2/client/cli/cli_test.go
  x/spot/client/testutil/suite.go
  x/sudo/cli/cli_test.go
  x/sudo/cli/gen_root_test.go
  x/tokenfactory/cli/cli_test.go
Labels: type: tests

#1653 ci: use cache for based on the go.sum for dependencies for faster GH action execution
  .github/workflows/golangci-lint.yml
  .github/workflows/integration-tests.yml
  .github/workflows/unit-tests.yml
Labels: skip-changelog, type: ci

#1656 feat(perp): Make the collateral denom a stateful collections.Item
  CHANGELOG.md
  app/keepers.go
  proto/nibiru/perp/v2/genesis.proto
  proto/nibiru/perp/v2/tx.proto
  wasmbinding/exec_perp_test.go
  wasmbinding/exec_test.go
  wasmbinding/querier_perp_test.go
  x/common/address.go
  x/common/address_test.go
  x/common/constants.go
  x/common/error.go
  x/common/testutil/cli/network.go
  x/common/testutil/genesis/perp_genesis.go
  x/common/testutil/testapp/testapp.go
  x/perp/v2/client/cli/cli_test.go
  x/perp/v2/integration/action/dnr.go
  x/perp/v2/integration/action/margin.go
  x/perp/v2/integration/action/market.go
  x/perp/v2/integration/action/tx.go
  x/perp/v2/integration/assertion/market.go
  x/perp/v2/keeper/admin.go
  x/perp/v2/keeper/admin_test.go
  x/perp/v2/keeper/amm.go
  x/perp/v2/keeper/amm_test.go
  x/perp/v2/keeper/clearing_house.go
  x/perp/v2/keeper/clearing_house_test.go
  x/perp/v2/keeper/dnr_test.go
  x/perp/v2/keeper/keeper.go
  x/perp/v2/keeper/liquidate.go
  x/perp/v2/keeper/liquidate_test.go
  x/perp/v2/keeper/margin.go
  x/perp/v2/keeper/margin_test.go
  x/perp/v2/keeper/msg_server.go
  x/perp/v2/keeper/msg_server_test.go
  x/perp/v2/keeper/settlement_test.go
  x/perp/v2/keeper/withdraw.go
  x/perp/v2/keeper/withdraw_test.go
  x/perp/v2/module/genesis.go
  x/perp/v2/module/genesis_test.go
  x/perp/v2/types/codec.go
  x/perp/v2/types/collateral.go
  x/perp/v2/types/errors.go
  x/perp/v2/types/expected_keepers.go
  x/perp/v2/types/genesis.go
  x/perp/v2/types/genesis.pb.go
  x/perp/v2/types/genesis_test.go
  x/perp/v2/types/market_test.go
  x/perp/v2/types/msgs.go
  x/perp/v2/types/msgs_test.go
  x/perp/v2/types/tx.pb.go
  x/sudo/keeper/keeper.go
  x/tokenfactory/keeper/msg_server.go
  x/tokenfactory/types/state.go
Labels: type: enhancement

#1669 feat(perp): Create query for the stateful collateral metadata
  CHANGELOG.md
  proto/nibiru/perp/v2/query.proto
  x/perp/v2/client/cli/cli_test.go
  x/perp/v2/client/cli/query.go
  x/perp/v2/client/cli/tx.go
  x/perp/v2/integration/action/query.go
  x/perp/v2/keeper/grpc_query.go
  x/perp/v2/keeper/grpc_query_test.go
  x/perp/v2/module/genesis_test.go
  x/perp/v2/module/module.go
  x/perp/v2/types/query.pb.go
  x/perp/v2/types/query.pb.gw.go
Labels: type: tests, type: enhancement
