Repository NibiruChain/nibiru, pull requests merged in 2023-10, with the labels that each got.

#1619 fix: ci not showing errors
  contrib/make/test.mk
Labels: skip-changelog

#1617 fix(app): non-nil snapshot manager is not guarantted in testapp
  CHANGELOG.md
  app/app.go
Labels: type: fix/bug

#1607 feat(tokenfactory): execute msgs for CreateDenom, ChangeAdmin, UpdateModuleParams
  CHANGELOG.md
  proto/nibiru/tokenfactory/v1/event.proto
  proto/nibiru/tokenfactory/v1/query.proto
  proto/nibiru/tokenfactory/v1/tx.proto
  x/common/testutil/cli/query.go
  x/common/testutil/sample.go
  x/devgas/v1/client/cli/tx.go
  x/sudo/types/msgs.go
  x/tokenfactory/cli/cli_test.go
  x/tokenfactory/cli/query.go
  x/tokenfactory/cli/tx.go
  x/tokenfactory/keeper/genesis.go
  x/tokenfactory/keeper/grpc_query.go
  x/tokenfactory/keeper/keeper_test.go
  x/tokenfactory/keeper/msg_server.go
  x/tokenfactory/keeper/msg_server_test.go
  x/tokenfactory/keeper/store.go
  x/tokenfactory/module.go
  x/tokenfactory/types/codec.go
  x/tokenfactory/types/codec_test.go
  x/tokenfactory/types/errors.go
  x/tokenfactory/types/event.pb.go
  x/tokenfactory/types/genesis.go
  x/tokenfactory/types/query.pb.go
  x/tokenfactory/types/query.pb.gw.go
  x/tokenfactory/types/state.go
  x/tokenfactory/types/state_test.go
  x/tokenfactory/types/tx.pb.go
  x/tokenfactory/types/tx_msgs.go
  x/tokenfactory/types/tx_msgs_test.go
Labels: type: fix/bug, type: enhancement

#1614 refactor(proto): Use explicit namespacing on proto imports for #1608
  CHANGELOG.md
  proto/nibiru/devgas/v1/genesis.proto
  proto/nibiru/devgas/v1/query.proto
  proto/nibiru/epochs/v1/genesis.proto
  proto/nibiru/epochs/v1/query.proto
  proto/nibiru/inflation/v1/query.proto
  proto/nibiru/oracle/v1/event.proto
  proto/nibiru/oracle/v1/genesis.proto
  proto/nibiru/oracle/v1/query.proto
  proto/nibiru/oracle/v1/tx.proto
  proto/nibiru/perp/v2/event.proto
  proto/nibiru/perp/v2/genesis.proto
  proto/nibiru/perp/v2/query.proto
  proto/nibiru/perp/v2/tx.proto
  proto/nibiru/spot/v1/event.proto
  proto/nibiru/spot/v1/genesis.proto
  proto/nibiru/spot/v1/pool.proto
  proto/nibiru/spot/v1/query.proto
  proto/nibiru/spot/v1/tx.proto
  proto/nibiru/stablecoin/v1/events.proto
  proto/nibiru/stablecoin/v1/genesis.proto
  proto/nibiru/stablecoin/v1/params.proto
  proto/nibiru/stablecoin/v1/query.proto
  proto/nibiru/stablecoin/v1/tx.proto
  proto/nibiru/sudo/v1/event.proto
  proto/nibiru/sudo/v1/query.proto
Labels: type: refactor

#1620 feat(tokenfactory): tx msgs for mint and burn
  CHANGELOG.md
  app/keepers.go
  go.mod
  go.sum
  proto/nibiru/tokenfactory/v1/event.proto
  proto/nibiru/tokenfactory/v1/tx.proto
  x/tokenfactory/cli/cli_test.go
  x/tokenfactory/cli/tx.go
  x/tokenfactory/keeper/genesis_test.go
  x/tokenfactory/keeper/grpc_query.go
  x/tokenfactory/keeper/grpc_query_test.go
  x/tokenfactory/keeper/keeper_test.go
  x/tokenfactory/keeper/msg_server.go
  x/tokenfactory/keeper/msg_server_test.go
  x/tokenfactory/keeper/store.go
  x/tokenfactory/keeper/store_test.go
  x/tokenfactory/module_test.go
  x/tokenfactory/types/codec.go
  x/tokenfactory/types/codec_test.go
  x/tokenfactory/types/errors.go
  x/tokenfactory/types/event.pb.go
  x/tokenfactory/types/genesis.go
  x/tokenfactory/types/state_test.go
  x/tokenfactory/types/tx.pb.go
  x/tokenfactory/types/tx_msgs.go
  x/tokenfactory/types/tx_msgs_test.go
Labels: type: enhancement

#1606 fix(perp): emit MarketUpdatedEvents even in the absence of index price
  CHANGELOG.md
  x/perp/v2/module/abci.go
Labels: type: fix/bug

#1631 fix(.goreleaser.yml): Load version for wasmvm dynamically
  .goreleaser.yml
  CHANGELOG.md
  contrib/scripts/release_pre_darwin.sh
  contrib/scripts/release_pre_linux.sh
Labels: type: fix/bug

#1635 feat(chaosnet): two chains with hermes relayer
  contrib/docker-compose/README.md
  contrib/docker-compose/docker-compose-chaosnet.yml
  contrib/docker/chaosnet.Dockerfile
  contrib/scripts/chaosnet.sh
  contrib/templates/hermes.toml
  contrib/templates/nibiru-0-validator-mnemonic
  contrib/templates/nibiru-1-validator-mnemonic
Labels: skip-changelog

#1638 test(tokenfactory)!: integration test core logic with a real smart contract using `nibiru-std`
  CHANGELOG.md
  app/keepers.go
  x/common/testutil/events.go
  x/common/testutil/events_test.go
  x/common/testutil/path.go
  x/common/testutil/testutil_test.go
  x/perp/v2/module/abci_test.go
  x/tokenfactory/fixture/fixture.go
  x/tokenfactory/fixture/nibi_stargate.wasm
  x/tokenfactory/keeper/grpc_query.go
  x/tokenfactory/keeper/grpc_query_test.go
  x/tokenfactory/keeper/keeper_test.go
  x/tokenfactory/keeper/wasm_test.go
Labels: type: tests, type: enhancement

#1646 feat(wasmbinding)!: whitelisted stargate queries for QueryRequest::Stargate: auth, bank, gov, tokenfactory, epochs, inflation, oracle, sudo, devgas
  CHANGELOG.md
  app/app.go
  app/keepers.go
  proto/nibiru/epochs/v1/query.proto
  wasmbinding/stargate_query.go
  wasmbinding/stargate_query_test.go
  wasmbinding/wasm.go
  x/devgas/v1/types/export.go
  x/epochs/README.md
  x/epochs/client/cli/query.go
  x/epochs/keeper/grpc_query.go
  x/epochs/keeper/grpc_query_test.go
  x/epochs/types/export.go
  x/epochs/types/query.pb.go
  x/epochs/types/query.pb.gw.go
  x/inflation/types/export.go
  x/oracle/types/export.go
  x/perp/v2/types/export.go
  x/spot/types/export.go
  x/stablecoin/types/events.pb.go
  x/stablecoin/types/genesis.pb.go
  x/stablecoin/types/params.pb.go
  x/stablecoin/types/query.pb.go
  x/stablecoin/types/query.pb.gw.go
  x/stablecoin/types/tx.pb.go
  x/stablecoin/types/tx.pb.gw.go
  x/sudo/types/export.go
  x/tokenfactory/types/export.go
Labels: type: fix/bug, type: enhancement

#1651 feat(openapi): generate openapi.yml with Ignite CLI for use with Swagger
  CHANGELOG.md
  config.yml
  go.mod
  go.sum
  tools/ignite-config.yml
  tools/ignite-openapi.sh
  tools/tools.go
Labels: type: docs, type: enhancement
