Repository NibiruChain/nibiru, pull requests merged in 2023-12, with the labels that each got.

#1694 ci: replace `master` with `main`
  .github/workflows/docker-publish.yml
  .github/workflows/e2e-wasm.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/integration-tests.yml
  .github/workflows/pr-title-lint.yml
  .github/workflows/proto-lint.yml
  .github/workflows/unit-tests.yml
Labels: skip-changelog

#1698 ci: bump to golang v1.21
  .github/workflows/golangci-lint.yml
  .github/workflows/integration-tests.yml
  .github/workflows/sims.yml
  .github/workflows/unit-tests.yml
  CHANGELOG.md
  Dockerfile
  contrib/docker/chaosnet.Dockerfile
  contrib/docker/goreleaser.Dockerfile
  contrib/make/release.mk
  contrib/scripts/release_pre_darwin.sh
  go.mod
  go.sum
Labels: dependencies

#1703 chore(deps): collections to v0.4.0 for math.Int value encoder
  CHANGELOG.md
  go.mod
  go.sum
  x/perp/v2/keeper/dnr.go
  x/perp/v2/keeper/dnr_int_encoder_test.go
  x/perp/v2/keeper/keeper.go
Labels: type: refactor, dependencies

#1707 fix: Update CHANGELOG.md
  CHANGELOG.md
Labels: type: fix/bug, skip-changelog

#1709 ci: test chaosnet script in CI after build
  .github/workflows/unit-tests.yml
  CHAOSNET.md
  contrib/scripts/chaosnet.sh
  x/perp/v2/integration/action/position.go
Labels: type: tests, skip-changelog, type: ci

#1711 docs(README): Fix hyperlinks + sync with fresh docs
  README.md
Labels: type: docs, skip-changelog

#1712 refactor(inflation): make inflation disabled by default
  CHANGELOG.md
  x/inflation/keeper/hooks_test.go
  x/inflation/keeper/inflation_test.go
  x/inflation/types/inflation_calculation_test.go
  x/inflation/types/params.go
Labels: P: Urgent / High prio

#1710 refactor(perp): Clean and organize module errors for x/perp
  CHANGELOG.md
  x/perp/v2/keeper/admin_test.go
  x/perp/v2/keeper/amm_test.go
  x/perp/v2/keeper/clearing_house.go
  x/perp/v2/keeper/clearing_house_test.go
  x/perp/v2/keeper/margin.go
  x/perp/v2/keeper/swap_test.go
  x/perp/v2/keeper/twap_test.go
  x/perp/v2/types/amm.go
  x/perp/v2/types/amm_test.go
  x/perp/v2/types/errors.go
  x/perp/v2/types/msgs.go
  x/perp/v2/types/msgs_test.go
Labels: type: refactor

#1721 ci: remove temp directory caching which causes stale libs
  contrib/docker/chaosnet.Dockerfile
Labels: skip-changelog

#1722 docs: update chaosnet readme
  CHAOSNET.md
Labels: type: docs, skip-changelog

#1726 ci: remove ld_classic flag
  contrib/make/build.mk
Labels: skip-changelog

#1727 ci: goreleaser latest workflow with dist folder
  .dockerignore
  .github/workflows/goreleaser-latest.yml
  contrib/docker/goreleaser.Dockerfile
  contrib/make/release.mk
Labels: skip-changelog, github_actions, type: ci

#1732 docs(chaosnet): add ibc commands
  CHAOSNET.md
Labels: type: docs, skip-changelog

#1728 test(devgas-cli): CLI tests for devgas txs
  CHANGELOG.md
  x/devgas/v1/client/cli/cli_test.go
Labels: type: tests

#1735 test(simulation): re-enable simulation tests
  .github/workflows/sims.yml
  .github/workflows/simulation-tests.yml
  CHANGELOG.md
  app/app.go
  app/export.go
  app/keepers.go
  app/upgrades.go
  contrib/make/simulation.mk
  simapp/README.md
  simapp/params.json
  simapp/sim_test.go
  simapp/state_test.go
  x/common/testutil/testapp/testapp.go
  x/sudo/module.go
  x/sudo/simulation/genesis.go
Labels: type: tests

#1753 ci: remove sim test from PRs
  .github/workflows/simulation-tests.yml
Labels: skip-changelog

#1754 refactor(decode-base64): clean code improvements and fn docs
  CHANGELOG.md
  cmd/nibid/cmd/decode_base64.go
Labels: type: refactor
