Repository NibiruChain/nibiru, pull requests merged in 2024-06, with the labels that each got.

#1910 chore: add v1.4.0 upgrade handler
  app/upgrades.go
  app/upgrades/v1_4_0/constants.go
Labels: skip-changelog

#1917 test(e2e): 1. Generated smart contract types for ethers. 2. TypeScript support. 3. Formatter
  .github/workflows/e2e-evm.yml
  .gitignore
  CHANGELOG.md
  e2e/evm/.nvmrc
  e2e/evm/bun.lockb
  e2e/evm/justfile
  e2e/evm/package-lock.json
  e2e/evm/package.json
  e2e/evm/prettier.config.mjs
  e2e/evm/test/basic_queries.test.js
  e2e/evm/test/basic_queries.test.ts
  e2e/evm/test/contract_infinite_loop_gas.test.js
  e2e/evm/test/contract_infinite_loop_gas.test.ts
  e2e/evm/test/contract_send_nibi.test.js
  e2e/evm/test/contract_send_nibi.test.ts
  e2e/evm/test/erc20.test.js
  e2e/evm/test/erc20.test.ts
  e2e/evm/test/setup.js
  e2e/evm/test/setup.ts
  e2e/evm/tsconfig.json
  e2e/evm/types/ethers-contracts/FunTokenCompiled.ts
  e2e/evm/types/ethers-contracts/InfiniteLoopGasCompiled.ts
  e2e/evm/types/ethers-contracts/ReceiveNibiCompiled.ts
  e2e/evm/types/ethers-contracts/SendNibiCompiled.ts
  e2e/evm/types/ethers-contracts/common.ts
  e2e/evm/types/ethers-contracts/factories/FunTokenCompiled__factory.ts
  e2e/evm/types/ethers-contracts/factories/InfiniteLoopGasCompiled__factory.ts
  e2e/evm/types/ethers-contracts/factories/ReceiveNibiCompiled__factory.ts
  e2e/evm/types/ethers-contracts/factories/SendNibiCompiled__factory.ts
  e2e/evm/types/ethers-contracts/factories/index.ts
  e2e/evm/types/ethers-contracts/index.ts
Labels: type: tests, type: refactor

#1912 test(evm): unit tests for evm_ante
  CHANGELOG.md
  app/evmante_can_transfer.go
  app/evmante_can_transfer_test.go
  app/evmante_emit_event.go
  app/evmante_emit_event_test.go
  app/evmante_eth.go
  app/evmante_fee_checker.go
  app/evmante_fee_checker_test.go
  app/evmante_fees.go
  app/evmante_fees_test.go
  app/evmante_gas_consume.go
  app/evmante_gas_consume_test.go
  app/evmante_gas_wanted.go
  app/evmante_gas_wanted_test.go
  app/evmante_handler_test.go
  app/evmante_increment_sender_seq.go
  app/evmante_increment_sender_seq_test.go
  app/evmante_reject_msgs_test.go
  app/evmante_setup_ctx.go
  app/evmante_setup_ctx_test.go
  app/evmante_sigverify.go
  app/evmante_sigverify_test.go
  app/evmante_validate_basic.go
  app/evmante_validate_basic_test.go
  app/evmante_verify_eth_acc.go
  app/evmante_verify_eth_acc_test.go
  contrib/make/test.mk
  x/evm/tx.go
Labels: type: tests

#1937 ci(docker): fix chaosnet and add docker compose profiles
  CHAOSNET.md
  contrib/docker-compose/README.md
  contrib/docker-compose/docker-compose-chaosnet.yml
  contrib/docker-compose/docker-compose-multi-node.yml
  contrib/make/chaosnet.mk
  contrib/scripts/chaosnet.sh
Labels: skip-changelog

#1936 feat(evm): EVM fungible token protobufs and encoding tests
  CHANGELOG.md
  e2e/evm/test/contract_send_nibi.test.ts
  eth/hex.go
  eth/hex_test.go
  eth/state_encoder.go
  proto/eth/evm/v1/evm.proto
  proto/eth/evm/v1/genesis.proto
  x/evm/access_list_test.go
  x/evm/const.go
  x/evm/events.go
  x/evm/evm.go
  x/evm/evm.pb.go
  x/evm/evm_test.go
  x/evm/genesis.pb.go
  x/evm/keeper/evm_state.go
  x/evm/keeper/funtoken_state.go
  x/evm/keeper/keeper.go
  x/evm/query_test.go
Labels: type: enhancement, x: evm
