Repository NibiruChain/nibiru, pull requests merged in 2024-01, with the labels that each got.

#1759 test(sim): add sim genesis state for custom modules
  CHANGELOG.md
  x/devgas/v1/module.go
  x/devgas/v1/simulation/genesis.go
  x/inflation/module.go
  x/inflation/simulation/genesis.go
  x/perp/v2/module/module.go
  x/perp/v2/simulation/genesis.go
  x/spot/module.go
  x/spot/module_simulation.go
  x/spot/simulation/genesis.go
  x/sudo/simulation/genesis.go
  x/tokenfactory/module.go
  x/tokenfactory/simulation/genesis.go
Labels: type: tests

#1757 chore: remove mentions of bindings for creating the market.
  wasmbinding/bindings/msg.go
  wasmbinding/exec_perp.go
  wasmbinding/exec_perp_test.go
  wasmbinding/exec_test.go
  wasmbinding/message_plugin.go
Labels: skip-changelog

#1752 feat(oracle): MsgEditOracleParams sudo tx msg as part of #1642
  CHANGELOG.md
  app/keepers.go
  proto/nibiru/oracle/v1/oracle.proto
  proto/nibiru/oracle/v1/tx.proto
  x/oracle/keeper/keeper.go
  x/oracle/keeper/msg_server.go
  x/oracle/keeper/sudo.go
  x/oracle/keeper/sudo_test.go
  x/oracle/keeper/test_utils.go
  x/oracle/types/errors.go
  x/oracle/types/expected_keeper.go
  x/oracle/types/msgs.go
  x/oracle/types/oracle.pb.go
  x/oracle/types/tx.pb.go
  x/oracle/types/tx.pb.gw.go
  x/sudo/doc.go
Labels: type: enhancement

#1751 docs: add adr-1 proposal for msg server and keeper consistency.
  .gitignore
  docs/adr/00-adr-template.md
  docs/adr/01-adr-msg-server-keeper.md
  docs/adr/README.md
Labels: type: docs, skip-changelog

#1765 fix(inflation): small fixes and tests
  x/inflation/types/inflation_calculation.go
  x/inflation/types/inflation_calculation_test.go
  x/inflation/types/params.go
Labels: skip-changelog

#1772 chore: fix typos
  INSTALL.md
  contrib/scripts/e2e/localnet.sh
  contrib/scripts/localnet.sh
  x/spot/README.md
Labels: skip-changelog

#1781 test: bring back e2e wasm
  .github/workflows/e2e-wasm.yml
  contrib/scripts/e2e/deploy-wasm.sh
  contrib/scripts/e2e/localnet.sh
Labels: skip-changelog
